/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacktestsRouteImport } from './routes/backtests'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MacroRouteImport } from './routes/macro'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as StocksTickerRouteImport } from './routes/stocks.$ticker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestsRoute = BacktestsRouteImport.update({
  id: '/backtests',
  path: '/backtests',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MacroRoute = MacroRouteImport.update({
  id: '/macro',
  path: '/macro',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksTickerRoute = StocksTickerRouteImport.update({
  id: '/stocks/$ticker',
  path: '/stocks/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtests': typeof BacktestsRoute
  '/companies': typeof CompaniesRoute
  '/login': typeof LoginRoute
  '/macro': typeof MacroRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/sources': typeof SourcesRoute
  '/watchlist': typeof WatchlistRoute
  '/events/$id': typeof EventsIdRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtests': typeof BacktestsRoute
  '/companies': typeof CompaniesRoute
  '/login': typeof LoginRoute
  '/macro': typeof MacroRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/sources': typeof SourcesRoute
  '/watchlist': typeof WatchlistRoute
  '/events/$id': typeof EventsIdRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtests': typeof BacktestsRoute
  '/companies': typeof CompaniesRoute
  '/login': typeof LoginRoute
  '/macro': typeof MacroRoute
  '/notifications': typeof NotificationsRoute
  '/portfolio': typeof PortfolioRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/sources': typeof SourcesRoute
  '/watchlist': typeof WatchlistRoute
  '/events/$id': typeof EventsIdRoute
  '/stocks/$ticker': typeof StocksTickerRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtests'
    | '/companies'
    | '/login'
    | '/macro'
    | '/notifications'
    | '/portfolio'
    | '/scanner'
    | '/settings'
    | '/signals'
    | '/sources'
    | '/watchlist'
    | '/events/$id'
    | '/stocks/$ticker'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtests'
    | '/companies'
    | '/login'
    | '/macro'
    | '/notifications'
    | '/portfolio'
    | '/scanner'
    | '/settings'
    | '/signals'
    | '/sources'
    | '/watchlist'
    | '/events/$id'
    | '/stocks/$ticker'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/backtests'
    | '/companies'
    | '/login'
    | '/macro'
    | '/notifications'
    | '/portfolio'
    | '/scanner'
    | '/settings'
    | '/signals'
    | '/sources'
    | '/watchlist'
    | '/events/$id'
    | '/stocks/$ticker'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestsRoute: typeof BacktestsRoute
  CompaniesRoute: typeof CompaniesRoute
  LoginRoute: typeof LoginRoute
  MacroRoute: typeof MacroRoute
  NotificationsRoute: typeof NotificationsRoute
  PortfolioRoute: typeof PortfolioRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  SourcesRoute: typeof SourcesRoute
  WatchlistRoute: typeof WatchlistRoute
  EventsIdRoute: typeof EventsIdRoute
  StocksTickerRoute: typeof StocksTickerRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtests': {
      id: '/backtests'
      path: '/backtests'
      fullPath: '/backtests'
      preLoaderRoute: typeof BacktestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macro': {
      id: '/macro'
      path: '/macro'
      fullPath: '/macro'
      preLoaderRoute: typeof MacroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks/$ticker': {
      id: '/stocks/$ticker'
      path: '/stocks/$ticker'
      fullPath: '/stocks/$ticker'
      preLoaderRoute: typeof StocksTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestsRoute: BacktestsRoute,
  CompaniesRoute: CompaniesRoute,
  LoginRoute: LoginRoute,
  MacroRoute: MacroRoute,
  NotificationsRoute: NotificationsRoute,
  PortfolioRoute: PortfolioRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  SourcesRoute: SourcesRoute,
  WatchlistRoute: WatchlistRoute,
  EventsIdRoute: EventsIdRoute,
  StocksTickerRoute: StocksTickerRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
